### ISSUE TITLE
Double logging when using rootpy

### ISSUE THREAD

**Issue by iarspider** [rootpy/rootpy#721] opened 2016-12-01 13:01 UTC
I'm using Python's logging module in my project and I've wanted to use rootpy to properly log  ROOT errors and warnings in the code. However, I'm unable to figure out how to make rootpy use my existing logger (or how to affect rootpy's own logger).

Minimal working example:
```
import rootpy.ROOT as ROOT
import logging

from rootpy import log
from rootpy.logger import LiteralFilter
log = log["/dqmtest"]
log["/ROOT.TROOT.Append"].addFilter(LiteralFilter(["Replacing existing TH1",]))

logger = None

def setup_logging(logfile):
    global logger

    print ("Setup logging")
    logger = logging.getLogger("dqmtest")
    # rootpy_log = logging.getLogger("rootpy")
    handler = logging.StreamHandler()
    handler.setFormatter(
        logging.Formatter('%(asctime)s [%(name)s:%(levelname)s] %(message)s',
                      datefmt='%H:%M:%S'))
    # handler.setLevel(logging.error)

    file_handler = logging.FileHandler(logfile, "w")
    file_handler.setFormatter(logging.Formatter(fmt="%(asctime)s [%(name)s:%(levelname)s] %(message)s"))
    # file_handler.setLevel(logging.DEBUG)

    logger.addHandler(handler)
    logger.addHandler(file_handler)
    # rootpy_log.addHandler(handler)
    # rootpy_log.addHandler(file_handler)

def main():
    setup_logging("example.log")

    logger.error("Before any ROOT calls")    

    h1 = ROOT.TH1D("name", "title", 100, 0, 100)
    h2 = ROOT.TH1D("name", "other title", 100, 0, 100)

    logger.error("After ROOT warning")

if __name__ == '__main__':
    main()
```

Produced output:
```
Setup logging
13:59:07 [dqmtest:ERROR] Before any ROOT calls
WARNING:ROOT.TROOT.Append] Replacing existing TH1: name (Potential memory leak).
13:59:07 [dqmtest:ERROR] After ROOT warning
ERROR:dqmtest] After ROOT warning
```

OS Ubuntu 16.04 (x64), Python 2.7.12, rootpy 0.8.3, ROOT 5.34.30 (built from source).

**Comment by iarspider** [comment] 2016-12-01 13:02
Also log filtering isn't working, but that is probably a result of logging not working properly.

**Comment by ndawe** [comment] 2016-12-02 01:22
Thanks for the MWE. I'll have a look.

**Comment by ndawe** [comment] 2016-12-02 01:53
It's case of multiple handlers duplicating messages up the logging hierarchy. I think the problem is that rootpy isn't checking if a handler already exists before adding one.

**Comment by ndawe** [comment] 2016-12-02 05:19
rootpy adds a StreamHandler to the root (top-level) logger if it doesn't already have a handler. Then you added a handler to ``logging.getLogger("dqmtest")``. The messages are duplicated because dqmtest still propagates messages up to the root logger. Your options are to either have ``logger.propagate = False`` so it doesn't propagate to rootpy's logger or add your handler to the top-level logger before importing rootpy for the first time ``logging.getLogger().addHandler(handler); import rootpy.ROOT as ROOT ...``

**Comment by iarspider** [comment] 2016-12-02 16:15
Thanks! Setting `propagate` to `False` fixed double logging. However, filtering doesn't seem to work:

```
import rootpy
import rootpy.ROOT as ROOT
import logging

logger = None
log = rootpy.log


class NoDictMessagesFilter(logging.Filter):
    def filter(self, record):
        return "Replacing existing TH1" not in record.msg


def setup_logging(logfile):
    global logger, log

    print ("Setup logging")
    logger = logging.getLogger("dqmtest")
    logger.propagate = False
    rootpy_log = logging.getLogger("ROOT")
    pfglogger = logging.getLogger("pfgutil")
    handler = logging.StreamHandler()
    handler.setFormatter(
        logging.Formatter('%(asctime)s [%(name)s:%(levelname)s] %(message)s',
                          datefmt='%H:%M:%S'))
    # handler.setLevel(logging.error)

    file_handler = logging.FileHandler(logfile, "w")
    file_handler.setFormatter(logging.Formatter(fmt="%(asctime)s [%(name)s:%(levelname)s] %(message)s"))
    # file_handler.setLevel(logging.DEBUG)

    logger.addHandler(handler)
    logger.addHandler(file_handler)
    pfglogger.addHandler(handler)
    pfglogger.addHandler(file_handler)
    rootpy_log.addHandler(handler)
    rootpy_log.addHandler(file_handler)

    # log["/ROOT.TROOT.Append"].addFilter(NoDictMessagesFilter())
    from rootpy.logger import LiteralFilter
    log["/ROOT.TROOT.Append"].addFilter(LiteralFilter(["Replacing existing TH1", ]))


def main():
    setup_logging("example.log")

    logger.error("Before any ROOT calls")

    h1 = ROOT.TH1D("name", "title", 100, 0, 100)
    h2 = ROOT.TH1D("name", "other title", 100, 0, 100)

    logger.error("After ROOT warning")


if __name__ == '__main__':
    main()
```
(`NoDictMessageFilter` works though).

**Comment by ndawe** [comment] 2016-12-05 03:14
LiteralFilter requires an exact match between complete strings so "Replacing existing TH1" won't work since that message is typically like "Replacing existing TH1: myname (Potential memory leak)."

**Comment by ndawe** [comment] 2016-12-05 03:15
Closing for now

**Closed by ndawe** 2016-12-05 03:15 UTC
